step 2 failure

diff --git a/.github/workflows/status-check.yaml b/.github/workflows/status-check.yaml
--- a/.github/workflows/status-check.yaml
+++ b/.github/workflows/status-check.yaml
@@ -5,13 +5,14 @@ jobs:
     job-1:
         runs-on: ubuntu-latest
         steps:
-            #- name: Fail
-            #  run: exit 1      ##este es por si queremos que falle y pase al job 2
             - name: Step 1
               run: sleep 20
+            - name: Fail
+              id: step-fail
+              run: exit 1      ##este es por si queremos que falle y pase al job 2
             - name: Runs on failure
-              if: failure()
-              run: echo "Runs only on failure"
+              if: failure() && steps.step-fail.conclusion == 'failure'
+              run: echo "Step 2 has failed"
             - name: Runs on success
               if: success()
               run: echo "Runs only on success"
